{% set name = "semi-ate-stil" %}
{% set version = "0.2.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Semi-ATE-STIL-{{ version }}.tar.gz
  sha256: 5abf5138a571769440fd6decce48e032bfe0a5255852b04e4c1ff1a4bc775536

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - lark
  run:
    - python >=3.7
    - lark
test:
  imports:
    - Semi_ATE
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Semi-ATE/STIL
  summary: Standard Tester Interface Library [IEEE1450] with python
  license: GPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - seimit
